adjective1 = input('Enter and  adjective: ')
noun1 = input('Enter a noun: ')
adjective2 = input('Enter an adjective: ')
verb1 = input('Enter a verb: ')
adjective3 = input('Enter an adjective: ')

print(f"Today I wnet to a {adjective1} zoo.")
#print(f"Today I saw a {adjective2} {animal}.")
print(f"In an exhibit, I saw a {noun1}")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"I was {adjective3}")